all:
	g++ -g -o cli cli.cpp 
	g++ -g -o cli_sockatmark cli_sockatmark.cpp
	g++ -g -o serv_select serv_select.cpp
	g++ -g -o serv_signal serv_signal.cpp
	g++ -g -o serv_sockatmark serv_sockatmark.cpp

