all:
	g++ -g -o cli_select cli_select.cpp
	g++ -g -o cli_poll cli_poll.cpp
	g++ -g -o cli_epoll cli_epoll.cpp
	g++ -g -o serv serv.cpp
	g++ -g -o serv_http serv_http.cpp
	g++ -g -o shutdown_r shutdown_r.cpp

clean:
	rm -f cli_select cli_poll cli_epoll serv serv_http shutdown_r